-- 코드를 입력하세요
SELECT
    P.PRODUCT_ID AS PRODUCT_ID, P.PRODUCT_NAME AS PRODUCT_NAME, (S.SUMV * P.PRICE) AS TOTAL_SALES
FROM
    FOOD_PRODUCT P
INNER JOIN
    (SELECT
    PRODUCT_ID, SUM(O.AMOUNT) AS SUMV
    FROM
        FOOD_ORDER O
    WHERE
        O.PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
    GROUP BY
        PRODUCT_ID) S
ON
    P.PRODUCT_ID = S.PRODUCT_ID
ORDER BY
    TOTAL_SALES DESC, PRODUCT_ID ASC;