-- 코드를 입력하세요
SELECT
    # CATEGORY, TOTAL_SALES
    B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES
FROM
    BOOK_SALES S
LEFT JOIN
    BOOK B
ON
    S.BOOK_ID = B.BOOK_ID
WHERE
    S.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY
    B.CATEGORY
ORDER BY
    B.CATEGORY ASC;